##
# environment.yml: Specification of a conda environment for use with
#      the Q# interoperability package.
##
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.
##

name: qsharp
channels:
    - conda-forge
    - pythonnet
dependencies:
    - numpy
    - pythonnet
    - qutip
    - matplotlib
    - pip:
        - qinfer
